@echo off
echo '----------------------------------------'
echo '---         _,met$$$$$gg.            ---'
echo '---      ,g$$$$$$$$$$$$$$$P.         ---'
echo '---     ,g$$P"     """Y$$.".         ---'
echo '---   ,$$P`              `$$$.       ---'
echo '---  `,$$P       ,ggs.     `$$b:     ---'
echo '---  `d$$`      ,$P`   .    $$$      ---'
echo '---   $$P      d$`     ,    $$P      ---'
echo '---   $$:      $$.   -     ,d$$      ---'
echo '---   $$;       Y$b._   _,d$P`       ---'
echo '---   Y$$.      `.`"Y$$$$P"`         ---'
echo '---   `$$b       "-.__               ---'
echo "---    `Y$$                          ---"
echo '---     `Y$$.           Desarrollo   ---'
echo '---       `$$b.           Web        ---'
echo '---         `Y$$b.`        NodeJS    ---'
echo '---            `"Y$b._      Quito    ---'
echo '---                `"""      Ecuador ---'
echo '----------------------------------------'
npm start
